services:
  - type: web
    name: registro-producao-api
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
    plan: free 